#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
#    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    # ImMemory
    url: jdbc:h2:mem:progressjournal
    username: sa
    password:
    schema: classpath:/db/shema.sql
    data: classpath:/db/data.sql
  h2.console.enabled: true

    #Heroku deploy
    #    initialization-mode: always
    #    platform: postgres
    #    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/userapp}
    #    username: ${SPRING_DATASOURCE_USERNAME:user}
    #    password: ${SPRING_DATASOURCE_PASSWORD:password}

  data.rest:
    #  https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.basic-settings
    basePath: /psjournal
    defaultPageSize: 20
    returnBodyOnCreate: true

logging:
  level:
    root: WARN
    edu.volkov.progressjournal: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%class{50}.%M:%L) - %green(%msg%n)"

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true


